const CFG=window.CELLENDAR_CONFIG,SCOPES=['User.Read','Files.ReadWrite'];let authApp=null,syncing=false;
async function initAuth(){if(CFG.clientId.startsWith('YOUR_'))return null;if(authApp)return authApp;authApp=new msal.PublicClientApplication({auth:{clientId:CFG.clientId,authority:`https://login.microsoftonline.com/${CFG.tenantId}`,redirectUri:location.origin+location.pathname},cache:{cacheLocation:'localStorage'}});if(authApp.initialize)await authApp.initialize();return authApp}
async function account(){const a=await initAuth();return a?.getAllAccounts()?.[0]||null}
async function login(){const a=await initAuth();if(!a)throw new Error('관리자가 Microsoft 클라이언트 ID를 아직 설정하지 않았습니다.');return (await a.loginPopup({scopes:SCOPES,prompt:'select_account'})).account}
async function logout(){const a=await initAuth(),u=await account();if(u)await a.logoutPopup({account:u,postLogoutRedirectUri:location.href})}
async function token(interactive=true){const a=await initAuth();let u=await account();if(!u&&interactive)u=await login();if(!u)throw new Error('로그인이 필요합니다.');try{return(await a.acquireTokenSilent({scopes:SCOPES,account:u})).accessToken}catch(e){if(!interactive)throw e;return(await a.acquireTokenPopup({scopes:SCOPES,account:u})).accessToken}}
function graphPath(){return CFG.workbookPath.split('/').map(encodeURIComponent).join('/')}
async function graph(path,{method='GET',body,accessToken,session}={}){const r=await fetch('https://graph.microsoft.com/v1.0'+path,{method,headers:{Authorization:`Bearer ${accessToken}`,...(body?{'Content-Type':'application/json'}:{}),...(session?{'workbook-session-id':session}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){let m='';try{m=(await r.json()).error?.message||''}catch{}const e=new Error(m||`Microsoft 연결 오류 (${r.status})`);e.status=r.status;const retry=r.headers.get('Retry-After');if(retry)e.retryAfter=Number(retry);throw e}return r.status===204?null:r.json()}
const dateKey=v=>{if(!v)return'';if(typeof v==='number')return new Date((v-25569)*86400000).toISOString().slice(0,10);return String(v).slice(0,10)};
const iso=v=>{if(!v)return null;if(typeof v==='number')return new Date((v-25569)*86400000).toISOString();const d=new Date(v);return isNaN(d)?null:d.toISOString()};
function fromRow(row){if(!row||(!row[1]&&!row[2]))return null;return{id:String(row[0]||crypto.randomUUID()),date:dateKey(row[1]),title:String(row[2]||''),memo:String(row[3]||''),color:String(row[4]||'#4f8ef7'),alarmTime:row[5]?String(row[5]).slice(0,5):'',updatedAt:iso(row[6])||new Date(0).toISOString(),deletedAt:iso(row[7]),source:'onedrive'}}
const toRow=e=>[e.id,e.date,e.title||'',e.memo||'',e.color||'#4f8ef7',e.alarmTime||'',e.updatedAt||new Date().toISOString(),e.deletedAt||''];
const fingerprint=e=>JSON.stringify([e.date,e.title,e.memo,e.color,e.alarmTime,e.deletedAt]);
function merge(local,remote){const m=new Map;[...remote,...local].forEach(e=>{const c=m.get(e.id);if(!c||new Date(e.updatedAt||0)>=new Date(c.updatedAt||0))m.set(e.id,e)});return[...m.values()].sort((a,b)=>(a.date+a.title).localeCompare(b.date+b.title))}
async function retryGraph(fn){try{return await fn()}catch(e){if(e.status===429){await new Promise(r=>setTimeout(r,Math.min((e.retryAfter||5)*1000,30000)));return fn()}throw e}}
async function fileExists(accessToken){try{await graph(`/me/drive/root:/${graphPath()}`,{accessToken});return true}catch(e){if(e.status===404)return false;throw e}}
async function syncNow(interactive=true){if(syncing)return null;syncing=true;try{const accessToken=await token(interactive);if(!await fileExists(accessToken)){const e=new Error('OneDrive에 Cellendar/캘린더(자동).xlsx 파일이 없습니다. 템플릿을 내려받아 해당 위치에 올려주세요.');e.code='FILE_MISSING';throw e}const base=`/me/drive/root:/${graphPath()}:/workbook`;const ses=await retryGraph(()=>graph(`${base}/createSession`,{method:'POST',body:{persistChanges:true},accessToken}));const session=ses?.id;const rows=`${base}/tables/${encodeURIComponent(CFG.tableName)}/rows`;const response=await retryGraph(()=>graph(rows,{accessToken,session}));const snapshot=JSON.parse(localStorage.getItem('remoteSnapshot')||'{}');const now=new Date().toISOString();const remote=(response.value||[]).map(x=>fromRow(x.values?.[0])).filter(Boolean);remote.forEach(e=>{if(snapshot[e.id]!==fingerprint(e))e.updatedAt=now});const local=(await allEvents()).map(e=>({...e,id:String(e.id||crypto.randomUUID()),updatedAt:e.updatedAt||now}));const merged=merge(local,remote);for(let i=0;i<(response.value||[]).length;i++)await retryGraph(()=>graph(`${rows}/itemAt(index=0)`,{method:'DELETE',accessToken,session}));if(merged.length)await retryGraph(()=>graph(`${rows}/add`,{method:'POST',body:{index:null,values:merged.map(toRow)},accessToken,session}));await replaceEvents(merged);localStorage.setItem('remoteSnapshot',JSON.stringify(Object.fromEntries(merged.map(e=>[e.id,fingerprint(e)]))));localStorage.setItem('lastSync',now);return{events:merged,total:merged.filter(e=>!e.deletedAt).length}}finally{syncing=false}}

