const CFG=window.CELLENDAR_CONFIG,SCOPES=['User.Read','Files.ReadWrite'];let authApp=null,syncing=false;
async function initAuth(){if(CFG.clientId.startsWith('YOUR_'))return null;if(authApp)return authApp;if(typeof msal==='undefined')throw new Error('Microsoft 로그인 모듈을 불러오지 못했습니다.');authApp=new msal.PublicClientApplication({auth:{clientId:CFG.clientId,authority:`https://login.microsoftonline.com/${CFG.tenantId}`,redirectUri:location.origin+location.pathname},cache:{cacheLocation:'localStorage'}});if(authApp.initialize)await authApp.initialize();return authApp}
async function account(){const a=await initAuth();return a?.getAllAccounts()?.[0]||null}
async function login(){const a=await initAuth();if(!a)throw new Error('관리자가 Microsoft 클라이언트 ID를 아직 설정하지 않았습니다.');return (await a.loginPopup({scopes:SCOPES,prompt:'select_account'})).account}
async function logout(){const a=await initAuth(),u=await account();if(u)await a.logoutPopup({account:u,postLogoutRedirectUri:location.href})}
async function token(interactive=true){const a=await initAuth();let u=await account();if(!u&&interactive)u=await login();if(!u)throw new Error('로그인이 필요합니다.');try{return(await a.acquireTokenSilent({scopes:SCOPES,account:u})).accessToken}catch(e){if(!interactive)throw e;return(await a.acquireTokenPopup({scopes:SCOPES,account:u})).accessToken}}
function graphPath(){return CFG.workbookPath.split('/').map(encodeURIComponent).join('/')}
async function graph(path,{method='GET',body,accessToken,session}={}){const r=await fetch('https://graph.microsoft.com/v1.0'+path,{method,headers:{Authorization:`Bearer ${accessToken}`,...(body?{'Content-Type':'application/json'}:{}),...(session?{'workbook-session-id':session}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){let m='';try{m=(await r.json()).error?.message||''}catch{}const e=new Error(m||`Microsoft 연결 오류 (${r.status})`);e.status=r.status;const retry=r.headers.get('Retry-After');if(retry)e.retryAfter=Number(retry);throw e}return r.status===204?null:r.json()}
const dateKey=v=>{if(!v)return'';if(typeof v==='number')return new Date((v-25569)*86400000).toISOString().slice(0,10);return String(v).slice(0,10)};
const iso=v=>{if(!v)return null;if(typeof v==='number')return new Date((v-25569)*86400000).toISOString();const d=new Date(v);return isNaN(d)?null:d.toISOString()};
const HEADER_FIELDS={id:'ID',date:'날짜',title:'제목',memo:'메모',color:'색상',alarmTime:'알림시각',updatedAt:'수정시간',deletedAt:'삭제시간'};
function columnMap(headers){return Object.fromEntries(Object.entries(HEADER_FIELDS).map(([field,label])=>[field,headers.findIndex(h=>String(h||'').trim()===label)]))}
const field=(row,cols,name)=>cols[name]>=0?row[cols[name]]:null;
function fromRow(row,cols){if(!row||(!field(row,cols,'date')&&!field(row,cols,'title')))return null;return{id:String(field(row,cols,'id')||crypto.randomUUID()),date:dateKey(field(row,cols,'date')),title:String(field(row,cols,'title')||''),memo:String(field(row,cols,'memo')||''),color:String(field(row,cols,'color')||'#4f8ef7'),alarmTime:field(row,cols,'alarmTime')?String(field(row,cols,'alarmTime')).slice(0,5):'',updatedAt:iso(field(row,cols,'updatedAt'))||new Date(0).toISOString(),deletedAt:iso(field(row,cols,'deletedAt')),source:'onedrive'}}
function excelDate(v){if(!v)return'';if(typeof v==='number')return v;const [y,m,d]=String(v).slice(0,10).split('-').map(Number);return Date.UTC(y,m-1,d)/86400000+25569}
function toRow(e,cols,size){const row=Array(size).fill(''),set=(name,value)=>{if(cols[name]>=0)row[cols[name]]=value};set('id',e.id);set('date',excelDate(e.date));set('title',e.title||'');set('memo',e.memo||'');set('color',e.color||'#4f8ef7');set('alarmTime',e.alarmTime||'');set('updatedAt',e.updatedAt||new Date().toISOString());set('deletedAt',e.deletedAt||'');return row}
const fingerprint=e=>JSON.stringify([e.date,e.title,e.memo,e.color,e.alarmTime,e.deletedAt]);
function merge(local,remote){const m=new Map;[...remote,...local].forEach(e=>{const c=m.get(e.id);if(!c||new Date(e.updatedAt||0)>=new Date(c.updatedAt||0))m.set(e.id,e)});return[...m.values()].sort((a,b)=>(a.date+a.title).localeCompare(b.date+b.title))}
async function retryGraph(fn){try{return await fn()}catch(e){if(e.status===429){await new Promise(r=>setTimeout(r,Math.min((e.retryAfter||5)*1000,30000)));return fn()}throw e}}
async function fileExists(accessToken){try{await graph(`/me/drive/root:/${graphPath()}`,{accessToken});return true}catch(e){if(e.status===404)return false;throw e}}
async function syncNow(interactive=true){if(syncing)return null;syncing=true;try{const accessToken=await token(interactive);if(!await fileExists(accessToken)){const e=new Error('OneDrive에 Cellendar/캘린더(자동).xlsx 파일이 없습니다. 템플릿을 내려받아 해당 위치에 올려주세요.');e.code='FILE_MISSING';throw e}const base=`/me/drive/root:/${graphPath()}:/workbook`;const ses=await retryGraph(()=>graph(`${base}/createSession`,{method:'POST',body:{persistChanges:true},accessToken}));const session=ses?.id,table=`${base}/tables/${encodeURIComponent(CFG.tableName)}`;const header=await retryGraph(()=>graph(`${table}/headerRowRange`,{accessToken,session}));const headers=header?.values?.[0]||['ID','날짜','제목','메모','색상','알림시각','수정시간','삭제시간'],cols=columnMap(headers);const rows=`${table}/rows`;const response=await retryGraph(()=>graph(rows,{accessToken,session}));const snapshot=JSON.parse(localStorage.getItem('remoteSnapshot')||'{}');const now=new Date().toISOString();const remote=(response.value||[]).map(x=>fromRow(x.values?.[0],cols)).filter(Boolean);remote.forEach(e=>{if(snapshot[e.id]!==fingerprint(e))e.updatedAt=now});const local=(await allEvents()).map(e=>({...e,id:String(e.id||crypto.randomUUID()),updatedAt:e.updatedAt||now}));const merged=merge(local,remote),values=merged.map(e=>toRow(e,cols,headers.length)),existing=(response.value||[]).length,blank=Array(headers.length).fill('');for(let i=0;i<Math.min(existing,values.length);i++)await retryGraph(()=>graph(`${rows}/itemAt(index=${i})/range`,{method:'PATCH',body:{values:[values[i]]},accessToken,session}));if(values.length>existing)await retryGraph(()=>graph(`${rows}/add`,{method:'POST',body:{index:null,values:values.slice(existing)},accessToken,session}));for(let i=values.length;i<existing;i++)await retryGraph(()=>graph(`${rows}/itemAt(index=${i})/range`,{method:'PATCH',body:{values:[blank]},accessToken,session}));await replaceEvents(merged);localStorage.setItem('remoteSnapshot',JSON.stringify(Object.fromEntries(merged.map(e=>[e.id,fingerprint(e)]))));localStorage.setItem('lastSync',now);return{events:merged,total:merged.filter(e=>!e.deletedAt).length}}finally{syncing=false}}

